-- GENERATED BY PGADMIN

-- Table: public.attempt

-- DROP TABLE IF EXISTS public.attempt;

CREATE TABLE IF NOT EXISTS public.attempt
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    answer character varying COLLATE pg_catalog."default" NOT NULL,
    date date NOT NULL,
    topic character varying COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT attempt_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.attempt
    OWNER to postgres;


-- Table: public.question

-- DROP TABLE IF EXISTS public.question;

CREATE TABLE IF NOT EXISTS public.question
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    text text COLLATE pg_catalog."default" NOT NULL,
    topic text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT question_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.question
    OWNER to postgres;